Default: &defaults
  database: liscrabble.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: liscrabble_test.sqlite3
  <<: *defaults

Staging:
  database: liscrabble_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: liscrabble_production.sqlite3
  poolsize: 100
  <<: *defaults
